"""
Refactoring guides for generated unit tests.

These guides provide best practices for cleaning up and improving
unit tests generated by Keploy.
"""

PYTHON_REFACTOR_GUIDE = """
## Python Test Refactoring Guidelines

### CRITICAL: REFACTOR ONLY - DO NOT ADD NEW TESTS
- ONLY refactor existing tests generated by Keploy
- Do NOT create, delete (unless duplicate), or change logic of test cases
- KEEP the same number of test cases
- FOCUS on code quality, structure, and naming

### CODE STANDARDS & STRUCTURE

- Follow AAA Pattern: Arrange → Act → Assert
- Naming: `test_should_[expected_result]_when_[condition]`
- Use pytest fixtures (`@pytest.fixture`) for reusable setup
- Use class-based grouping (`class TestClassName`) for related scenarios
- Use `conftest.py` for shared fixtures
- Use `MagicMock` / `patch` for mocking; use native pytest style (not `unittest.TestCase`)
- Keep each test focused on ONE behavior

### CONSTRAINTS
- No integration/e2e tests — mock all external dependencies
- Do NOT test private methods (`__` prefix) directly
- Do NOT leave placeholder comments or import unused modules

### OUTPUT FORMAT
1. Full Python test file with all imports
2. conftest.py snippet if shared fixtures needed
3. Summary table: | Test Function Name | Scenario Covered | Expected Result |
"""

JAVA_REFACTOR_GUIDE = """
## Java Test Refactoring Guidelines

### CRITICAL: REFACTOR ONLY - DO NOT ADD NEW TESTS
- ONLY refactor existing tests generated by Keploy
- Do NOT create, delete (unless duplicate), or change logic of test cases
- KEEP the same number of test cases
- FOCUS on code quality, structure, and naming

### CODE STANDARDS & STRUCTURE

- Follow AAA Pattern: Arrange → Act → Assert
- Naming: `Test_should_[ExpectedResult]_when_[Condition]`
- Use `@ExtendWith(MockitoExtension.class)` for service layer tests
- Use `@ParameterizedTest` + `@MethodSource`/`@CsvSource` for data-driven tests
- Use `@Nested` classes for grouping, `@DisplayName` for descriptions
- Use AssertJ (`assertThat`) instead of JUnit `assertEquals`
- Use `ArgumentCaptor` to verify mocked method arguments
- Use `@BeforeEach` for shared setup

### CONSTRAINTS
- No Spring context (`@SpringBootTest`) — pure unit tests only
- Do NOT test private methods directly
- Do NOT use Hamcrest — use AssertJ only
- Do NOT leave placeholder comments

### OUTPUT FORMAT
1. Full Java test class with all imports
2. Summary table: | Test Method Name | Scenario Covered | Expected Result |
"""
