"""
Refactoring guides for generated unit tests.

These guides provide best practices for cleaning up and improving
unit tests generated by Keploy.
"""

PYTHON_REFACTOR_GUIDE = """
## Python Test Refactoring Guidelines

### CRITICAL: REFACTOR ONLY - DO NOT ADD NEW TESTS
**IMPORTANT:**
- **ONLY** refactor existing tests generated by Keploy
- **DO NOT** create new test cases
- **DO NOT** delete existing tests (unless duplicate)
- **KEEP** the same number of test cases
- **FOCUS** on code quality, structure, and naming
**Your task is to:**
- Clean up code structure
- Improve readability
- Apply best practices
- Remove code smells

**NOT to:**
- Write new tests
- Increase coverage
- Change test logic

### CODE STANDARDS & STRUCTURE

NOT ADD ANY TEST CASE after Keploy generates tests, ONLY refactor the test file to ensure clean, maintainable code.

- Follow AAA Pattern Strictly: Every test function MUST follow the Arrange-Act-Assert pattern
    Arrange  → set up data, mocks, fixtures
    Act      → call the function under test
    Assert   → verify the outcome

- Test Function Naming Convention: `test_should_[expected_result]_when_[condition]`
  Example:
    **Good:**
    - `test_should_raise_not_found_when_user_id_does_not_exist()`
    - `test_should_return_user_when_id_is_valid()`
    - `test_should_throw_validation_error_when_email_is_invalid()`

    **Bad:**
    - `test_user_not_found()` - Missing expected result
    - `test1()` - No meaning
    - `test_user()` - Too vague

- Use pytest Fixtures: Create reusable setup with `@pytest.fixture`
- Use class-based grouping (class TestClassName) for related scenarios
- Use conftest.py for shared fixtures across test modules
- Use MagicMock / patch as context manager or decorator for mocking
- Use mocker fixture (pytest-mock) if preferred over unittest.mock
- Keep each test focused on ONE behavior only
- Use descriptive docstrings on test functions when logic is complex

### CONSTRAINTS
- Do NOT write integration or end-to-end tests
- Do NOT hit real databases, APIs, or file systems — mock everything external
- Do NOT use unittest.TestCase style — use native pytest style only
- Do NOT test private methods (prefixed with __) directly
- Do NOT leave placeholder comments like "# add more tests" — be complete
- Do NOT import unused modules in the test file

### OUTPUT FORMAT
For each generated test file, provide:
1. Full Python test file with all imports
2. conftest.py snippet if shared fixtures are needed
3. A short summary table at the end listing:
   | Test Function Name | Scenario Covered | Expected Result |
"""

JAVA_REFACTOR_GUIDE = """
## Java Test Refactoring Guidelines

### CRITICAL: REFACTOR ONLY - DO NOT ADD NEW TESTS
**IMPORTANT:**
- **ONLY** refactor existing tests generated by Keploy
- **DO NOT** create new test cases
- **DO NOT** delete existing tests (unless duplicate)
- **KEEP** the same number of test cases
- **FOCUS** on code quality, structure, and naming

### CODE STANDARDS & STRUCTURE
NOT ADD ANY TEST CASE after Keploy generates tests, ONLY refactor the test file to ensure clean, maintainable code.

- Follow AAA Pattern Strictly: Every test method MUST follow the Arrange-Act-Assert pattern
    Arrange  → set up data and mocks
    Act      → call the method under test
    Assert   → verify the outcome

- Test Method Naming Convention: `Test_should_[ExpectedResult]_when_[Condition]`
  Example:
    **Good:**
    - `Test_should_ThrowNotFoundException_when_UserIdDoesNotExist()`
    - `Test_should_ReturnUser_when_IdIsValid()`
    - `Test_should_ThrowValidationError_when_EmailIsInvalid()`

    **Bad:**
    - `testUserNotFound()` - Missing expected result
    - `test1()` - No meaning
    - `testUser()` - Too vague

- Use @ExtendWith(MockitoExtension.class) for service layer tests
- Use @ParameterizedTest + @MethodSource or @CsvSource for data-driven tests
- Use @Nested classes to group related test scenarios
- Use @DisplayName for human-readable test descriptions
- Use AssertJ (assertThat) instead of JUnit assertEquals
- Use ArgumentCaptor to verify arguments passed to mocked methods
- Use @BeforeEach for shared setup, avoid redundancy

### CONSTRAINTS
- Do NOT use Spring context (@SpringBootTest) — pure unit tests only
- Do NOT test private methods directly — test via public interface
- Do NOT write integration tests
- Do NOT use Hamcrest — use AssertJ only
- Do NOT leave placeholder comments like "// add more tests" — be complete

### OUTPUT FORMAT
For each generated test class, provide:
1. Full Java test class with all imports
2. A short summary table at the end listing:
   | Test Method Name | Scenario Covered | Expected Result |
"""
